import Head from "next/head";

const TodoItems = [
  {
    color: "#EF233C",
    title: "Organize photo shoot",
    date: "Today",
    checked: false,
    tags: ["work", "hooli"],
  },
  {
    color: "#B2B6FF",
    title: "Buy milk",
    date: "Today",
    checked: false,
    tags: ["Grocery"],
  },
  {
    color: "#FFE9B2",
    title: "Set up meeting w/ Globex",
    date: "Tomorrow",
    checked: false,
    tags: ["work"],
  },
  {
    color: "#FFC6C6",
    title: "Renew Password",
    date: "Tomorrow",
    checked: false,
    tags: ["personal"],
  },
  {
    color: "#C6FAFF",
    title: "Checklist LA trip",
    date: "Tomorrow",
    checked: false,
    tags: ["work"],
  },
];

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="flex justify-center my-10">
        <div className="w-[600px] shadow-lg border dark:border-slate-600 min-h-[90vh] mx-3 sm:mx-8 rounded-3xl p-6 sm:p-9 overflow-x-hidden overflow-y-auto">
          <div className="flex justify-between items-center">
            <h1 className="text-2xl underline decoration-wavy decoration-2 underline-offset-4">
              Todo
            </h1>
            <button className="capitalize bg-[#6e48f5] px-3.5 py-2 rounded-md text-sm sm:text-base text-white">
              create reminder +
            </button>
          </div>
          <div className="mt-6">
            <ul className="space-y-2">
              {TodoItems.map((item) => (
                <li
                  className="border rounded-lg p-3 dark:border-slate-700"
                  key={item.title}
                >
                  <div className="flex justify-start items-center gap-3 sm:gap-5">
                    <div
                      style={{ borderColor: item.color }}
                      className={`min-w-[20px] min-h-[20px] border-2 rounded-full resize-none]`}
                    ></div>
                    <div className="leading-none flex flex-col sm:flex-row justify-between items-start sm:items-center w-full gap-3">
                      <div>
                        <h3 className="font-semibold text-base sm:text-lg">
                          {item.title}
                        </h3>
                        <span className="text-xs sm:text-sm">{item.date}</span>
                      </div>
                      <div className="mr-2 space-x-2">
                        {item.tags.map((tag, idx) => (
                          <span
                            key={idx}
                            className="bg-gray-100 dark:bg-gray-700 font-medium capitalize text-xs sm:text-sm px-2 py-1.5 rounded-md"
                          >
                            {tag}
                          </span>
                        ))}
                      </div>
                    </div>
                  </div>
                </li>
              ))}
            </ul>
          </div>
          <div className="mt-6">
            <h2 className="font-semibold mb-3">Completed</h2>
            <ul className="opacity-50">
              <li className="border rounded-lg p-3 dark:border-slate-700">
                <div className="flex justify-start items-center gap-3 sm:gap-5">
                  <div
                    className={`min-w-[20px] min-h-[20px] border-2 rounded-full resize-none]`}
                  ></div>
                  <div className="leading-none flex flex-col sm:flex-row justify-between items-start sm:items-center w-full gap-3">
                    <div>
                      <h3 className="font-semibold text-base sm:text-lg line-through">
                        Set up meeting w/ Globex
                      </h3>
                      <span className="text-xs sm:text-sm line-through">
                        Tomorrow
                      </span>
                    </div>
                    <div className="mr-2 space-x-2">
                      <span className="bg-gray-100 dark:bg-gray-700 font-medium capitalize text-xs sm:text-sm px-2 py-1.5 rounded-md">
                        work
                      </span>
                    </div>
                  </div>
                </div>
              </li>
            </ul>
          </div>
        </div>
      </div>
    </>
  );
}
